export { default as About } from "./About"
export { default as Blogs } from "./Blogs"
export { default as Contact } from "./Contact"
export { default as HomePage } from "./HomePage"
export { default as Products } from "./Products"
export { default as Blog } from "./Blog"
export { default as Random } from "./Random"
export { default as Details } from "./Details"
export { default as All } from "./All"
export {default as NotFound} from "./NotFound"